import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;


/*
 * FileProcessor.java : This class is used to Read and Write the data needed by the Recommendation System.
 */
public class FileProcessor
{
	
	int m;
	int n;
	int rating[][];
	String output_file;
	String input_file;
	
	public FileProcessor(int mIn, int nIn, String inputfileIn, String outputfileIn)
	{
		m = mIn;
		n = nIn;
		rating = new int[m][n];
		output_file = outputfileIn;
		input_file = inputfileIn;
	}
	// Read's the file and store the data of each user and item and its rating in a rating array.
	public int[][] readFromFile()
	{
		
		Scanner s = null;
		File filename = new File(input_file);
		try
		{
			s = new Scanner(filename);
			System.out.println("\n"+filename + " file successfully opened for reading");
			System.out.println("Reading Data from file to process.");
			for (int i = 0; i < m; i++)
			{
				for (int j = 0; j < n; j++)
				{
					rating[i][j] = 0;
				}
			}
			int user = 0;
			int items = 0;
			while (s.hasNext())
			{
				user = s.nextInt(); // read ProdID and store it in i.
				items = s.nextInt(); // read ProdID and store it in j.
				rating[user - 1][items - 1] = s.nextInt(); // read Rating and store it in
													// the rating Array.
			}
			s.close();

		}
		catch (FileNotFoundException ex)
		{
			System.err.println(filename + " File Not Found");
			ex.printStackTrace();
			System.exit(-1);
		}
		return rating;
	}

	// Writes the data generated by the recommendation system to the output file.
	public void writeToFile(int[][] ratingIn)
	{
		int[][] rating = ratingIn;
		try
		{
			File file = new File(output_file);

			if (!file.exists())
			{
				file.createNewFile();
			}

			FileWriter fw = new FileWriter(file.getAbsoluteFile());
			BufferedWriter bw = new BufferedWriter(fw);
			System.out.println("Writing Data to the output file.");
			for (int i = 0; i < m; i++)
			{
				for (int j = 0; j < n; j++)
				{
					bw.write((i + 1) + " " + (j + 1) + " " + rating[i][j] + "\n");
				}
			}
			System.out.println("\nOutput created...");
			bw.close();
		}
		catch (IOException e)
		{
			System.out.println("Cannot open file to Write data.\n");
			e.printStackTrace();
			System.exit(-1);
		}
	}

}
